version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: songvat
      POSTGRES_PASSWORD: postgres_sample
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # app:
  #   container_name: SP_container
  #   image: node:14
  #   restart: always
  #   working_dir: /usr/src/app
  #   volumes:
  #     - .:/usr/src/app
  #   command: sh -c "npm install && npx ts-node-dev src/index.ts"
  #   environment:
  #     DATABASE_URL: postgres://songvat:postgres_sample@postgres:5432/mydatabase
  #   depends_on:
  #     - postgres

volumes:
  postgres-data:
